# Generated by Django 4.0.4 on 2023-04-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
